version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"  # якщо потрібно доступ ззовні

volumes:
  db_data:
